### PR TITLE
Fix #113 -- Add rate_limit_type attribute

### LINKED ISSUE #113: raising RateLimitError seems to be broken
During #59, this line was introduced:
https://github.com/Thermondo/closeio/commit/f16ba2a8c9f1d81b5a378c78772f668cba2be81e#diff-74dc48de5fb2c93a2c7921b5d64010edR32

I tried to reproduce this piece with next snippet:

```
>>> from closeio.exceptions import CloseIOError, RateLimitError

>>> error_info
{'error': {'message': 'API call count exceeded for this period', 'rate_reset': 0.870663, 'rate_limit': 40, 'rate_window': 1, 'rate_limit_type': 'key'}}

>>> raise RateLimitError(**error_info['error'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amureki/.virtualenvs/thermondo-backend/lib/python3.6/site-packages/closeio/exceptions.py", line 28, in __init__
    super(RateLimitError, self).__init__(*args, **kwargs)
TypeError: RateLimitError does not take keyword arguments
RateLimitError does not take keyword arguments
```

### PR DESCRIPTION
**Pull request by codingjoe**
* Add rate_limit_type to RateLimitError
* Do not pass any arguments to RateLimitError super init method, to avoid problems with API updates.

### CODE REVIEW

**Comment by amureki** [comment]
@codingjoe I've added test for this, if you don't mind. :)

**Comment by amureki** [comment]
@codingjoe is release process automated? Can you check it, please?

**Comment by codingjoe** [comment]
@amureki you need to tag the version to release. I'll do it.

**Comment by codingjoe** [comment]
Released in 0.5.0

**Pull request merged**
