### PR TITLE
Fixes type issue

### PR DESCRIPTION
**Pull request by codingjoe**
Content can be bytes in python 3

https://app.getsentry.com/thermondo/thermondo-backend/issues/101657667/

### CODE REVIEW

**Comment by samifahed** [comment]
@codingjoe all the tests failed here

**Comment by codingjoe** [comment]
@samifahed so it is working ;) The only thing that makes the test fail is an api change. But see how nicely the error is being displayed :P

**Comment by samifahed** [comment]
@syphar not sure if we should merge and always have failing tests, need your opinion here

**Comment by syphar** [comment]
closing in favor for #22

**Pull request closed without merging**
